version: '2'
services:
  ia-nbi:
    build:
      context: .
      dockerfile: Dockerfile-tests
    entrypoint: /test.sh
    links:
     - postgres
    environment:
     - repo_host postgres
     - repo_port 5432
     - repo_user sonata
     - repo_pass sonatatest
    volumes:
     - ./reports:/adaptor/target

  postgres:
    image: ntboes/postgres-uuid
    ports:
     - "5432"
    environment:
     - POSTGRES_PASSWORD=sonata
     - POSTGRES_USER=sonatatest
